# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0033_merge_20170509_1710'),
    ]

    operations = [
        # migrations.AlterIndexTogether(
        #     name='celerytask',
        #     index_together=set([]),
        # ),
        migrations.RemoveField(
            model_name='celerytask',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='started_by',
        ),
        migrations.DeleteModel(
            name='CeleryProviderTask',
        ),
        migrations.RemoveField(
            model_name='normalizeddata',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='harvestlog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enqueued'), (1, 'In Progress'), (2, 'Failed'), (3, 'Succeeded'), (4, 'Rescheduled'), (6, 'Forced'), (7, 'Skipped'), (8, 'Retrying'), (9, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
