# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('share', '0034_auto_20170511_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.TaskResult')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
    ]
