# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('share', '0035_celerytaskresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytaskresult',
            name='taskresult_ptr',
        ),
        migrations.DeleteModel(
            name='CeleryTaskResult',
        ),
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
    ]
