# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import share.models.fields
import share.models.logs


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0036_auto_20170511_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTaskResult',
        ),
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.TextField()),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50)),
                ('task_id', models.UUIDField(db_index=True)),
                ('meta', share.models.fields.DateTimeAwareJSONField(editable=False)),
                ('celery_meta', share.models.fields.DateTimeAwareJSONField(editable=False)),
                ('result', share.models.fields.DateTimeAwareJSONField(editable=False)),
                ('task_name', models.TextField()),
                ('traceback', models.TextField(blank=True, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('share_version', models.TextField(default=share.models.logs.get_share_version, editable=False)),
            ],
            options={
                'verbose_name': 'Task Result',
                'verbose_name_plural': 'Task Results',
            },
        ),
    ]
