# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0037_auto_20170511_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskresult',
            name='task_name',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='celerytaskresult',
            name='traceback',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
