# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:38
from __future__ import unicode_literals

from django.db import migrations
import share.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0038_auto_20170511_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskresult',
            name='meta',
            field=share.models.fields.DateTimeAwareJSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='celerytaskresult',
            name='result',
            field=share.models.fields.DateTimeAwareJSONField(editable=False, null=True),
        ),
    ]
