# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0039_auto_20170511_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfig',
            name='harvest_after',
            field=models.TimeField(default='02:00'),
        ),
        migrations.AddField(
            model_name='sourceconfig',
            name='harvest_interval',
            field=models.DurationField(default='1 day'),
        ),
    ]
