# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0041_sourceconfig_backharvesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizeddata',
            name='tasks',
            field=models.ManyToManyField(to='share.CeleryTaskResult'),
        ),
        migrations.AlterField(
            model_name='celerytaskresult',
            name='correlation_id',
            field=models.TextField(blank=True),
        ),
    ]
